### ISSUE TITLE
Project onboarding tracking

### ISSUE THREAD

**Issue by matthewfeickert** [scientific-python/upload-nightly-action#112]
(Migrated from https://github.com/scientific-python/upload-nightly-action/issues/30#issuecomment-1960398919)

Running list for me to track the status of groups getting onboarded:

> [!NOTE] 
> check off once have successfully uploaded wheels

* [x] `h5py` https://github.com/scientific-python/upload-nightly-action/issues/51#issuecomment-1960373356
* [x] `awkward`, `awkward-cpp`, `uproot` https://github.com/scientific-python/upload-nightly-action/issues/29#issuecomment-1960383256
   - [x] `awkward-cpp`
   - [x] `awkward`
   - [x] `uproot`
* [x] `shapely` https://github.com/scientific-python/upload-nightly-action/issues/63#issuecomment-1960393895
* [x] `dipy` https://github.com/scientific-python/upload-nightly-action/issues/45#issuecomment-1961736482
* [x] `sunpy` https://github.com/scientific-python/upload-nightly-action/issues/50#issuecomment-1961748520
* [x] `contourpy` https://github.com/contourpy/contourpy/issues/362#issuecomment-1962771358
* [x] `PyTables` https://github.com/PyTables/PyTables/issues/1115#issuecomment-1962825660
* [x] `PyWavelets` https://github.com/scientific-python/upload-nightly-action/issues/75#issuecomment-1986144872
* [x] `pyarrow` https://github.com/apache/arrow/issues/40216#issuecomment-2018437734
* [x] `cython` https://github.com/scientific-python/upload-nightly-action/issues/80#issuecomment-2145636316
* [x] `pydata-sphinx-theme` https://github.com/scientific-python/upload-nightly-action/issues/82
* [x] `pillow` https://github.com/scientific-python/upload-nightly-action/issues/84
* [x] `pyproj` https://github.com/scientific-python/upload-nightly-action/issues/87#issuecomment-2254354375
* [x] `ipykernel` https://github.com/scientific-python/upload-nightly-action/issues/110 
* [x] `sympy` https://github.com/scientific-python/upload-nightly-action/issues/111
* [x] `python-flint` https://github.com/scientific-python/upload-nightly-action/issues/111
